@extends(Auth::user()->Home)
@section('body-home')
    @component('components.catalogo')
        @slot('buttons')
            @include('SIGSAS.xFiles.UI_Kit.__menu_catalogo')
        @endslot
        @slot('body_catalogo')
            @include('SIGSAS.User.__User.__user_list')
        @endslot
    @endcomponent
@endsection
